# #####################################################################
# Automatically generated by qmake (2.01a) Fr 5. Nov 13:39:21 2010
# #####################################################################
TEMPLATE = app
TARGET = BHYWI-22-E5_VTK
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    fdm.cpp
HEADERS += fdm.h
